### ISSUE TITLE
Day 1 --  Why 7?

### ISSUE THREAD

**Issue by nylocx** [tginsberg/advent-2019-kotlin#1]
Really like your solution to the problem, but I guess the `7` should be a `9` as eight will also give you a zero (8 / 2 = 2; 2 - 2 = 0)so you can terminate your recursion on anything smaller than 9.

**Comment by tginsberg** [comment]
Good catch! I'll fix it and credit you.

**Comment by tginsberg** [comment]
Fixed and credited. Thanks!
